---
# tasks file for tomcat-server
- name: Ensure Tomcat is installed
  package:
    name: 
      - tomcat
    state: latest
    update_cache: yes
  become: true

- name: Ensure Tomcat is running
  service:
    name: tomcat
    state: started