---
# tasks file for tomcat-server

- name: Ensure Tomcat is installed
  package:
    name: 
      - tomcat
      - tomcat-webapps
    state: latest
    update_cache: yes
- name: Ensure Tomcat is running
  service:
    name: tomcat
    state: started