---
# - name: Ensure epel is installed
#   yum:
#     name: epel-release
#     state: present
#   become: true

- name: Ensure python3 and pip3 are installed
  package:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  become: true
