galaxy_info:
  author: Mike Scott
  description: Get application distributable from s3 bucket
  company: NTT Data

  license: license (BSD, MIT)

  min_ansible_version: 1.2

  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
     - s3
     - webapp
     - war

dependencies: []
