---
- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Ensure {{ db_name }} db is present
  mysql_db:
    name: "{{ db_name }}"
    state: present
  become: true

- name: Ensure {{ db_user }} user is present
  mysql_user:
    name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
  become: true