---
- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- include: Amazon.yml
  when: ansible_distribution == "Amazon"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Ensure {{ db_name }} db is present
  mysql_db:
    name: "{{ db_name }}"
    login_host: "{{ db_host }}"
    login_user: "{{ db_admin_user }}"
    login_password: "{{ db_admin_password }}"
    state: present
  become: true

- name: Ensure {{ db_user }} user is present
  mysql_user:
    name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    login_host: "{{ db_host }}"
    login_user: "{{ db_admin_user }}"
    login_password: "{{ db_admin_password }}"
    state: present
  become: true