---
# tasks file for todo-webapp
# Get package from control /dist

- name: Copy War to tomcat
  copy:
    src: "dist/{{ app_package }}-{{ app_version }}.war"
    dest:  "{{ tomcat_home }}/webapps/todo.war"
  notify:
    - restart tomcat

- name: Ensure war is deployed
  wait_for:
    path:  "{{ tomcat_home }}/webapps/todo/WEB-INF"
    delay: 10
    timeout: 30
    state: present
    msg: "Specified todo app did not deploy"


- name: ensure application.properties is configured
  template: 
    src: templates/application.properties.j2
    dest: "{{ tomcat_home }}/webapps/todo/WEB-INF/classes/application.properties"
  notify:
    - restart tomcat