---
# tasks file for todo-webapp
# Get package onto control
- name: Ensure pip is installed
  local_action:
    module: package
    name: python-pip
    state: latest

- name: Ensure AWS python requirememnts are installed
  local_action:
    module: pip
    name:
      - boto
      - boto3
      - botocore
    state: present

- name: Ensure distribution directory is present
  local_action:
    module: file
    name: dist
    state: directory

- name: Get package from s3
  local_action:
    module: aws_s3
    bucket: "{{ app_dist_bucket }}"
    object: "/dist/{{ app_package }}-{{ app_version }}.war"
    dest: "dist/{{ app_package }}-{{ app_version }}.war"
    mode: get

- name: Copy War to tomcat
  copy:
    src: "dist/{{ app_package }}-{{ app_version }}.war"
    dest:  "{{ tomcat_home }}/webapps/todo.war"
  notify:
    - restart tomcat

- name: Ensure war is deployed
  wait_for:
    path:  "{{ tomcat_home }}/webapps/todo/WEB-INF"
    delay: 10
    timeout: 30
    state: present
    msg: "Specified todo app did not deploy"


- name: ensure application.properties is configured
  template: 
    src: templates/application.properties.j2
    dest: "{{ tomcat_home }}/webapps/todo/WEB-INF/classes/application.properties"
  notify:
    - restart tomcat