---
# tasks file for todo-webapp
# Get package onto control
- name: Ensure pip is installed
  package:
    name: python-pip
    state: latest

- name: Ensure AWS python requirememnts are installed
  pip:
    name:
      - boto
      - boto3
      - botocore
    state: present

- name: Ensure distribution directory is present
  file:
    name: dist
    state: directory

- name: Get package from s3
  aws_s3:
    bucket: "{{ app_dist_bucket }}"
    object: "/dist/{{ app_package }}-{{ app_version }}.war"
    dest: "dist/{{ app_package }}-{{ app_version }}.war"
    mode: get
    overwrite: different