---
# defaults file for todo-webapp
db_host: localhost
db_name: tododb
db_user: username
db_password: password

app_package: todo
app_version: '0.0.1-SNAPSHOT'

tomcat_package: tomcat
tomcat_home: '/usr/share/tomcat'
