---
# defaults file for todo-webapp
db_host: localhost
db_name: tododb
db_user: username
db_password: password

app_dist_bucket: 'com-nttdata-ta-demo'
app_package: todo
app_version: '0.0.1-SNAPSHOT'

tomcat_home: '/usr/share/tomcat'


