---
# tasks file for mysql-server
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Ensure mySQL is installed
  package:
    name: mysql-server
    state: latest
    update_cache: yes
  become: true

- name: Ensure mySQL service is running
  service:
    name: "{{ mysql_service }}"
    state: started
  become: true